// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/delivery.proto

package delivery

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryDeliverParameter struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDeliverParameter) Reset()         { *m = QueryDeliverParameter{} }
func (m *QueryDeliverParameter) String() string { return proto.CompactTextString(m) }
func (*QueryDeliverParameter) ProtoMessage()    {}
func (*QueryDeliverParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_97b0354d48dd2073, []int{0}
}

func (m *QueryDeliverParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeliverParameter.Unmarshal(m, b)
}
func (m *QueryDeliverParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeliverParameter.Marshal(b, m, deterministic)
}
func (m *QueryDeliverParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeliverParameter.Merge(m, src)
}
func (m *QueryDeliverParameter) XXX_Size() int {
	return xxx_messageInfo_QueryDeliverParameter.Size(m)
}
func (m *QueryDeliverParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeliverParameter.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeliverParameter proto.InternalMessageInfo

func (m *QueryDeliverParameter) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type DeliverInfo struct {
	LocationLat          float32  `protobuf:"fixed32,2,opt,name=location_lat,json=locationLat,proto3" json:"location_lat,omitempty"`
	LocationLng          float32  `protobuf:"fixed32,3,opt,name=location_lng,json=locationLng,proto3" json:"location_lng,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	DeliverGuyId         string   `protobuf:"bytes,5,opt,name=deliver_guy_id,json=deliverGuyId,proto3" json:"deliver_guy_id,omitempty"`
	DeliverGuyNumber     string   `protobuf:"bytes,6,opt,name=deliver_guy_number,json=deliverGuyNumber,proto3" json:"deliver_guy_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverInfo) Reset()         { *m = DeliverInfo{} }
func (m *DeliverInfo) String() string { return proto.CompactTextString(m) }
func (*DeliverInfo) ProtoMessage()    {}
func (*DeliverInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97b0354d48dd2073, []int{1}
}

func (m *DeliverInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverInfo.Unmarshal(m, b)
}
func (m *DeliverInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverInfo.Marshal(b, m, deterministic)
}
func (m *DeliverInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverInfo.Merge(m, src)
}
func (m *DeliverInfo) XXX_Size() int {
	return xxx_messageInfo_DeliverInfo.Size(m)
}
func (m *DeliverInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverInfo proto.InternalMessageInfo

func (m *DeliverInfo) GetLocationLat() float32 {
	if m != nil {
		return m.LocationLat
	}
	return 0
}

func (m *DeliverInfo) GetLocationLng() float32 {
	if m != nil {
		return m.LocationLng
	}
	return 0
}

func (m *DeliverInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DeliverInfo) GetDeliverGuyId() string {
	if m != nil {
		return m.DeliverGuyId
	}
	return ""
}

func (m *DeliverInfo) GetDeliverGuyNumber() string {
	if m != nil {
		return m.DeliverGuyNumber
	}
	return ""
}

// 结果
type DeliveryResult struct {
	OrderId              string         `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId               string         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserPhoneNumber      string         `protobuf:"bytes,3,opt,name=user_phone_number,json=userPhoneNumber,proto3" json:"user_phone_number,omitempty"`
	DeliveryAddress      string         `protobuf:"bytes,4,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DeliveryList         []*DeliverInfo `protobuf:"bytes,5,rep,name=delivery_list,json=deliveryList,proto3" json:"delivery_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeliveryResult) Reset()         { *m = DeliveryResult{} }
func (m *DeliveryResult) String() string { return proto.CompactTextString(m) }
func (*DeliveryResult) ProtoMessage()    {}
func (*DeliveryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_97b0354d48dd2073, []int{2}
}

func (m *DeliveryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryResult.Unmarshal(m, b)
}
func (m *DeliveryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryResult.Marshal(b, m, deterministic)
}
func (m *DeliveryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryResult.Merge(m, src)
}
func (m *DeliveryResult) XXX_Size() int {
	return xxx_messageInfo_DeliveryResult.Size(m)
}
func (m *DeliveryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryResult proto.InternalMessageInfo

func (m *DeliveryResult) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *DeliveryResult) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeliveryResult) GetUserPhoneNumber() string {
	if m != nil {
		return m.UserPhoneNumber
	}
	return ""
}

func (m *DeliveryResult) GetDeliveryAddress() string {
	if m != nil {
		return m.DeliveryAddress
	}
	return ""
}

func (m *DeliveryResult) GetDeliveryList() []*DeliverInfo {
	if m != nil {
		return m.DeliveryList
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_97b0354d48dd2073, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryDeliverParameter)(nil), "delivery.QueryDeliverParameter")
	proto.RegisterType((*DeliverInfo)(nil), "delivery.DeliverInfo")
	proto.RegisterType((*DeliveryResult)(nil), "delivery.DeliveryResult")
	proto.RegisterType((*Empty)(nil), "delivery.Empty")
}

func init() { proto.RegisterFile("protos/delivery.proto", fileDescriptor_97b0354d48dd2073) }

var fileDescriptor_97b0354d48dd2073 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0xfa, 0x30,
	0x18, 0xc7, 0x7f, 0x83, 0xdf, 0x18, 0x3e, 0x20, 0x48, 0xcd, 0x62, 0xf5, 0x22, 0x2e, 0x1e, 0xd0,
	0x18, 0x4c, 0xf0, 0xa6, 0x27, 0x8d, 0xc6, 0x2c, 0x21, 0x06, 0xb9, 0xe9, 0x65, 0x19, 0xb6, 0xe2,
	0x92, 0xb1, 0x92, 0xb6, 0x33, 0xe9, 0xcb, 0xf3, 0x55, 0xf8, 0x76, 0xcc, 0xba, 0x76, 0x80, 0x1a,
	0x6f, 0xfd, 0x7e, 0x9f, 0x4f, 0xfa, 0xfc, 0x05, 0x7f, 0xc9, 0x99, 0x64, 0xe2, 0x9c, 0xd0, 0x34,
	0x79, 0xa7, 0x5c, 0x0d, 0xb5, 0x46, 0x4d, 0xab, 0x83, 0x11, 0xf8, 0x8f, 0x39, 0xe5, 0xea, 0xb6,
	0x34, 0x26, 0x31, 0x8f, 0x17, 0x54, 0x52, 0x8e, 0xf6, 0xa1, 0xc9, 0x38, 0xa1, 0x3c, 0x4a, 0x08,
	0x76, 0xfa, 0xce, 0x60, 0x6b, 0xea, 0x69, 0x1d, 0x92, 0xe0, 0xc3, 0x81, 0x96, 0xe1, 0xc3, 0xec,
	0x95, 0xa1, 0x23, 0x68, 0xa7, 0xec, 0x25, 0x96, 0x09, 0xcb, 0xa2, 0x34, 0x96, 0xb8, 0xd6, 0x77,
	0x06, 0xb5, 0x69, 0xcb, 0x7a, 0xe3, 0x58, 0x6e, 0x22, 0xd9, 0x1c, 0xd7, 0xbf, 0x21, 0xd9, 0x1c,
	0x61, 0xf0, 0x62, 0x42, 0x38, 0x15, 0x02, 0xff, 0x2f, 0xf3, 0x19, 0x89, 0x8e, 0xa1, 0x63, 0xea,
	0x8d, 0xe6, 0xb9, 0x2a, 0x0a, 0x72, 0x35, 0xd0, 0x36, 0xee, 0x7d, 0xae, 0x42, 0x82, 0xce, 0x00,
	0xad, 0x53, 0x59, 0xbe, 0x98, 0x51, 0x8e, 0x1b, 0x9a, 0xdc, 0x59, 0x91, 0x0f, 0xda, 0x0f, 0x3e,
	0x1d, 0xe8, 0x98, 0x1e, 0xd4, 0x94, 0x8a, 0x3c, 0x95, 0x7f, 0x74, 0x8c, 0xf6, 0xc0, 0xcb, 0x45,
	0x19, 0xa9, 0xe9, 0x48, 0xa3, 0x90, 0x21, 0x41, 0xa7, 0xd0, 0xd3, 0x81, 0xe5, 0x1b, 0xcb, 0xa8,
	0xcd, 0x59, 0xd7, 0x48, 0xb7, 0x08, 0x4c, 0x0a, 0xbf, 0x4c, 0x89, 0x4e, 0xc0, 0x96, 0xa1, 0xa2,
	0xcd, 0x4e, 0xbb, 0xd6, 0xbf, 0x36, 0x1d, 0x5f, 0xc2, 0x76, 0x85, 0xa6, 0x89, 0x90, 0xd8, 0xed,
	0xd7, 0x07, 0xad, 0x91, 0x3f, 0xac, 0xf6, 0xb8, 0x36, 0xff, 0x6a, 0x0e, 0x6a, 0x9c, 0x08, 0x19,
	0x78, 0xe0, 0xde, 0x2d, 0x96, 0x52, 0x8d, 0x9e, 0xc0, 0xd5, 0xab, 0x45, 0x13, 0xe8, 0xad, 0xef,
	0x58, 0xe9, 0xa5, 0x1d, 0xae, 0xfe, 0xfa, 0xf5, 0x00, 0x0e, 0xf0, 0x8f, 0x64, 0x66, 0x50, 0xc1,
	0xbf, 0x1b, 0xff, 0x79, 0x77, 0x58, 0xdd, 0xd4, 0x95, 0x7d, 0xcc, 0x1a, 0xfa, 0xba, 0x2e, 0xbe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xdd, 0x5c, 0x20, 0x76, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryDeliveryInfo(ctx context.Context, in *QueryDeliverParameter, opts ...grpc.CallOption) (*DeliveryResult, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryDeliveryInfo(ctx context.Context, in *QueryDeliverParameter, opts ...grpc.CallOption) (*DeliveryResult, error) {
	out := new(DeliveryResult)
	err := c.cc.Invoke(ctx, "/delivery.Query/QueryDeliveryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryDeliveryInfo(context.Context, *QueryDeliverParameter) (*DeliveryResult, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryDeliveryInfo(ctx context.Context, req *QueryDeliverParameter) (*DeliveryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeliveryInfo not implemented")
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryDeliveryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeliverParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryDeliveryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delivery.Query/QueryDeliveryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryDeliveryInfo(ctx, req.(*QueryDeliverParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDeliveryInfo",
			Handler:    _Query_QueryDeliveryInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/delivery.proto",
}
