definitions:
  login.LoginResponse:
    properties:
      message:
        type: string
      token:
        type: string
      user_id:
        type: string
    type: object
  login.Response:
    properties:
      ctx_id:
        type: string
      message:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /get_public_key:
    get:
      description: get rsa public key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/login.Response'
  /login:
    get:
      description: 登录
      parameters:
      - description: 用户名
        in: formData
        name: user_name
        required: true
        type: string
      - description: 密码
        in: formData
        name: pass_word
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.LoginResponse'
swagger: "2.0"
